In [8]:
import pandas as pd
import numpy as np
import sklearn
import seaborn
import pickle

In [9]:
dfPhenotypes = pd.read_csv("sc3_Phase2_CN_GE_Phenotype.tsv",sep="\t")
dfPhenotypes = dfPhenotypes.replace(r'^\s*$', np.nan, regex=True)
dfPhenotypes = dfPhenotypes.replace(r'^IV', 4, regex=True)
dfPhenotypes = dfPhenotypes.replace(r'^III', 3, regex=True)
dfPhenotypes = dfPhenotypes.replace(r'^II', 2, regex=True)
dfPhenotypes = dfPhenotypes.replace(r'^I', 1, regex=True)
dfPhenotypes['WHO_GRADING'].replace(np.nan, 0, regex=True,inplace=True)
dfPhenotypes.head()

     PATIENTID     SEX   RACE  WHO_GRADING        CANCER_TYPE
0  patient_126    MALE  WHITE          2.0  OLIGODENDROGLIOMA
1  patient_140    MALE  WHITE          4.0                GBM
2  patient_163  FEMALE  WHITE          4.0                GBM
3  patient_193    MALE  WHITE          4.0                GBM
4  patient_197    MALE  WHITE          4.0                GBM

In [10]:
dfFeatures = pd.read_csv("sc3_Phase2_CN_GE_FeatureMatrix.tsv",sep="\t")
dfFeatures.head()

,PATIENTID,A1BG,A1BG.AS1,A1CF,A2M,A2M.AS1,A2ML1,A4GALT,A4GNT,AA06,...,22q11.22,22q11.23,22q12.1,22q12.2,22q12.3,22q13.1,22q13.2,22q13.31,22q13.32,22q13.33
0,patient_126,6.449641,6.959727,5.426469,11.871797,5.790700,6.967988,7.213648,6.089065,6.373173,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,patient_140,6.899503,6.575910,5.324229,11.881737,6.084898,6.600541,7.032983,6.059075,6.231159,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
2,patient_163,6.972283,6.579010,5.795912,13.089512,6.849555,5.375303,7.077586,6.433238,6.465994,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
3,patient_193,6.964364,6.938148,5.313100,12.083214,5.714333,5.627228,7.161048,5.744593,5.980872,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
4,patient_197,6.545566,6.775012,5.426674,12.712501,6.270268,5.355421,7.190568,5.972685,6.339993,...,0.0,0.0,1.418056,0.898075,1.756195,1.407025,1.139215,0.612589,0.0,0.0

In [11]:
dfMerged = pd.merge(dfPhenotypes,dfFeatures,how="inner",on="PATIENTID")
dfMerged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41 entries, 0 to 40
Columns: 20151 entries, PATIENTID to 22q13.33
dtypes: float64(20112), int64(35), object(4)
memory usage: 6.3+ MB

In [12]:
featuresFile = "sc3_phase1_features.txt"
with open(featuresFile) as f:
    featuresList = f.read().split(',')
print(featuresList)

['1p34.3', '19q12', 'CHI3L1', '14q31.3', '1q21.3', '1q22', '8q24.22', '7p12.1', '11q21', '9q34.12', '9p21.3', '9q33.1', '11q12.3', '5q33.2', '2q36.2', '4q24', '21q22.3', '9q34.11', '10q25.1', '8p12', '1p11.2', '8p21.3', '10p11.1', '11q25', '12q24.32', '6p11.2', 'GPR17', '12q13.13', '6p12.1', '12p12.1', '11p15.1', '4p14', '8p23.2', '5q11.2', '14q12', '6q16.1', '5q35.3', '21q11.2', '11q14.1', '11q13.1', 'SFRP2', '22q12.2', '12q21.1', '17q22', '11p11.12', '13q13.1', '11q13.4', '3q12.1', '2p14', '12q14.3', '2q37.3', 'CXCL14', 'SLC14A1', '3q25.31', '15q21.2', '21q21.1', '8p11.21', 'SUSD5', '15q22.32', '8q13.3', '11p15.4', '18q22.1', '6q24.3', '11q23.3', '9q21.33', '11p11.2', '15q26.2', '6p11.1', '12p12.2', '17q24.2', '18p11.22', '11q22.3', '12q14.1', '6p21.2', '11q24.2', '17p13.3', '11q11', '11q14.3', '3p14.2', '11q12.1', 'CHST9', 'GBP3', '15q25.2', '6p12.3', '16p12.2', '5q35.2', '11p15.3', '16p13.11', '6p25.3', '11p13', '12q24.31']

In [13]:
x_test = dfMerged[featuresList]

In [14]:
finalFile = "..\..\phase1\sc3_phase1\sc3_phase1_model.sav"
loaded_model = pickle.load(open(finalFile, 'rb'))
predictions = loaded_model.predict(x_test)
print(predictions)

[1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1]